---
- name: Start reset password
  shell: |
    #!/bin/bash
    echo "starting master-cli..."
    # 改密码
    redis-cli -p 6379 -a 123123 config set masterauth 111111
    redis-cli -p 6379 -a 123123 config set requirepass 111111
    # 重写config
    redis-cli -p 6379 -a 111111 config rewrite