---
- name: scaleUp bindvip
  shell: |
    #!/bin/bash
    str=`redis-cli -p "{{ redisServerPort }}" -a "{{ password }}" info replication | grep role | grep master`
    echo "$str"
    if [[ -z $str ]]; then
       echo "is slave"
    else
       echo "is master"
       vip=`ip addr |grep {{ vip }}/32`
       if [[ -z $vip ]]; then
          echo "vip is empty"
          ip addr add {{ vip }}/32 dev {{ network_card_interface }}
          echo "bindVIP end"
       fi
    fi
